name: robot-test

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install robot and depends
        run: |
          python -m pip install --upgrade pipenv
          pipenv install
      - name: Run test
        run: pipenv run robot tasks.robot
      - name: Archive test outputs
        uses: actions/upload-artifact@v3
        with:
          name: robot-output-artifacts
          path: output
          retention-days: 5
